## Research Awards {.central}

[Data Challenges]{.palevioletred}

-   **Best objective prediction**, Team Bayes Beyond the stars, [Stats Under the Stars 6](https://sus.econ.univpm.it/index.php?a=1) organized by Italian Statistical Society (June 20–21, 2023)

-   **Best prediction**, Team GIRLS, [Lab Data Challenges](https://www.dems.unimib.it/it/news/lab-data-challenges) organized by University of Milano-Bicocca (May 2021) 


[Grants]{.palevioletred}

-   Member of the research team for **AIRR Gateway Project**, *Reasoning-Enhanced Multimodal AI-Generated Content Detection*, PI: Prof. Giulia Livieri Co-PI: Prof. Chengchun Shi (May 2026--Aug 2026)

-   Member of the research team for **AIRR Gateway Project**, *Lowering the Computational Barrier: Resource- and Energy-Efficient Reinforcement Learning for LLM Reasoning*, PI: Prof. Chengchun Shi Co-PI: Prof. Giulia Livieri (Feb 2026--May 2026)

[Workshops]{.palevioletred}

-   **Selected participant** for [Data Research Camp](https://datascience.unifi.it/eccellenzadisia/past-events/data-research-camp-15-18-luglio-2024/) organized by Department of Statistics, Computer Science, Applications, University of Florence (July 15--18, 2024)